-- ============================
--  ROLES & USERS
-- ============================

create table public.role (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table public.app_user (
  id bigint generated by default as identity primary key,

  username text,
  name text,
  password text,
  email text,

  role_id bigint references public.role(id),

  created_at timestamptz default now()
);

-- optional but recommended: enforce uniqueness on username/email
create unique index if not exists uq_app_user_username on public.app_user (username);
create unique index if not exists uq_app_user_email on public.app_user (email);


-- ============================
--  FRIENDSHIPS
-- ============================

create table public.friendship (
  id bigint generated by default as identity primary key,

  requester_id bigint references public.app_user(id) on delete cascade,
  addressee_id bigint references public.app_user(id) on delete cascade,

  status text, -- FriendshipStatus as TEXT (REQUESTED, ACCEPTED, DECLINED, BLOCKED)

  created_at timestamptz default now()
);


-- ============================
--  FAVOURITE LOCATIONS
-- ============================

create table public.favourite_location (
  id bigint generated by default as identity primary key,

  user_id bigint references public.app_user(id) on delete cascade,

  name text,
  latitude double precision,
  longitude double precision,

  created_at timestamptz default now()
);


-- ============================
--  ACHIEVEMENTS
-- ============================

create table public.achievement (
  id bigint generated by default as identity primary key,

  name text,
  description text,
  criteria_type text,   -- e.g. "REPORTS", "TRIPS"
  criteria_value integer,
  icon_url text
);


-- ============================
--  USER ACHIEVEMENTS
-- ============================

create table public.user_achievement (
  id bigint generated by default as identity primary key,

  user_id bigint references public.app_user(id) on delete cascade,
  achievement_id bigint references public.achievement(id) on delete cascade,

  unlocked_at timestamptz,
  progress integer
);


-- ============================
--  HAZARD CATEGORIES & REPORTS
-- ============================

create table public.hazard_category (
  id bigint generated by default as identity primary key,
  name text
);

create table public.hazard_report (
  id bigint generated by default as identity primary key,

  title text,
  description text,
  latitude double precision,
  longitude double precision,

  category_id bigint references public.hazard_category(id),
  created_by_id bigint references public.app_user(id) on delete set null,

  status text, -- HazardStatus as TEXT (OPEN, VERIFIED, RESOLVED, REJECTED)

  created_at timestamptz default now()
);


-- ============================
--  VOTES
-- ============================

create table public.vote (
  id bigint generated by default as identity primary key,

  vote_type text, -- VoteType as TEXT (UPVOTE, DOWNVOTE)

  user_id bigint references public.app_user(id) on delete cascade,
  hazard_report_id bigint references public.hazard_report(id) on delete cascade,

  created_at timestamptz default now()
);

-- optional: prevent double-voting on same report by same user
create unique index if not exists uq_vote_user_hazard
  on public.vote (user_id, hazard_report_id);


-- ============================
--  LICENSE PLATE INFO
-- ============================

create table public.license_plate_info (
  id bigint generated by default as identity primary key,

  license_plate text,
  brand text,
  model text,
  year_of_manufacture integer,
  fuel_type text,

  fetched_at timestamptz,

  user_id bigint references public.app_user(id) on delete set null
);


-- ============================
--  STATISTICS
-- ============================

create table public.statistics (
  id bigint generated by default as identity primary key,

  user_id bigint unique references public.app_user(id) on delete cascade,

  total_trips integer,
  total_distance_km double precision,
  total_hazards_reported integer,
  total_votes integer
);


-- ============================
--  TRIPS
-- ============================

create table public.trip (
  id bigint generated by default as identity primary key,

  user_id bigint references public.app_user(id) on delete cascade,

  distance_km double precision,
  started_at timestamptz,
  ended_at timestamptz,

  start_location_id bigint references public.favourite_location(id),
  end_location_id bigint references public.favourite_location(id)
);
