spring.application.name=backend

spring.datasource.url=jdbc:postgresql://tripwire-db:5432/tripwiredb
spring.datasource.username=tripwire
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
