#pragma once

/**
 * Configuration for data source selection
 * Set DATA_SOURCE_MODE to either:
 *   - DATA_SOURCE_SIMULATED: Use simulated/test data
 *   - DATA_SOURCE_REAL: Use real OBD-II data (requires OBD hardware)
 */
#define DATA_SOURCE_SIMULATED 0
#define DATA_SOURCE_REAL 1

// ============================================
// CHANGE THIS TO SWITCH BETWEEN DATA SOURCES
// ============================================
#define DATA_SOURCE_MODE DATA_SOURCE_SIMULATED

// ============================================
// Telemetry sending configuration
// ============================================
#define LIVE_TELEMETRY_INTERVAL_MS 1000    // Send live data every 1 second
#define HISTORY_TELEMETRY_INTERVAL_MS 60000 // Send history data every 60 seconds

// ============================================
// Backend configuration
// ============================================
// These should be set in secrets.h or via build flags
#ifndef BACKEND_BASE_URL
#define BACKEND_BASE_URL "https://your-backend.com"
#endif

// DEVICE_ID is now auto-generated by DeviceIdentity system
// Only define DEVICE_ID in secrets.h if you want to manually override
// (not recommended - auto-generation is better)

#ifndef DEVICE_API_KEY
#define DEVICE_API_KEY "your-device-api-key"
#endif
